act: Fail if env.GITHUB_ACTION_PATH does not work

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -291,6 +291,12 @@ outputs:
 runs:
   using: 'composite'
   steps:
+    - name: act-broken
+      if: env.ACT && (github.action_path || env.GITHUB_ACTION_PATH) && (env.GITHUB_ACTION_PATH != github.action_path)
+      shell: bash
+      run: |
+        echo '::error ::This version of nektos/act is broken. See https://github.com/check-spelling/check-spelling/wiki/Breaking-Change:-Dropping-support-for-broken-act'
+        exit 1
     - name: act-windows-shim
       if: env.ACT
       shell: bash
